### ISSUE TITLE
Pad designators too big when rendering big components with small pins

### ISSUE THREAD

**Issue by ddavidebor** [issus/AltiumSharp#3]
When rendering big components with small pins, such as this microcontroller, the pad designators are too big and overlap

[IC_STMicroelectronics_STM32F429IIT6.zip](https://github.com/issus/AltiumSharp/files/3469636/IC_STMicroelectronics_STM32F429IIT6.zip)
![image](https://user-images.githubusercontent.com/9055742/62499553-6e72fe80-b7e3-11e9-86ab-595647b9041f.png)

**Comment by issus** [comment]
Try it again with the latest revisions
