### ISSUE TITLE
System.FormatException : Input string was not in a correct format

### ISSUE THREAD

**Issue by riccardocusatelli** [issus/AltiumSharp#9]
I've incurred in a not managed Exception when loading a .PcbLib with multiple footprints.
The execution is stopped on line 65 of Parameters.cs when: _data=""
Looks like it happens because AsEnumerable() add empty elements if the string _data contains empty strings (or is empty).
It works better if line 139 of file "Parameters.cs" is changed to:
```
if (!string.IsNullOrEmpty(item))
                    yield return new ParameterValue(item, '\0');
```

**Comment by issus** [comment]
can you please supply the pcblib you're having issues with?

**Comment by riccardocusatelli** [comment]
I will keep the file here temporary: [https://gofile.io/d/hguWEe](https://gofile.io/d/x7pVmq)

**Comment by issus** [comment]
Seems to be resolved after latest pull request.
